version: '3'
services:
  et-mongo:
    image: "mongo"
    container_name: "et-mongo"
    volumes:
     - et-cfgdb:/data/configdb
     - et-db:/data/db
    networks:
       et-network:
    restart: always   
    command: --auth
  et-server:
    image: "gameserver_et-server"
    container_name: "et-server"
    command: --appId=1 --appType=Manager --config=../Config/StartConfig/LocalAllServer.txt --runtimeMode=1
    #command: --appId=1 --appType=BenchmarkKCPServer --config=../Config/StartConfig/BenchmarkKCPServer.txt --mongoAlias=et-mongo
    #entrypoint: bash
    depends_on:
      - "et-mongo"
    volumes:
     - et-logs:/et-server/Logs/
    networks:
       et-network:
    restart: always
    hostname: et-server
    #tty: true
    stdin_open: true
    ports:
     - "10002:10002/tcp"
     - "10003:10003"
     - "10004:10004"
volumes:
  et-cfgdb:
  et-db:
  et-logs:
networks:
  et-network: